---
# Source: auth/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminui
  namespace: {{ $.Release.Namespace }}
  labels: {}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminui
  template:
    metadata:
      labels:
        app: adminui
    spec:
      securityContext: {}
      imagePullSecrets:
        - name: {{ .Values.regCredName }} 
      containers:
        - name: adminui
          securityContext: null
          image: {{ .Values.imageName }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            limits:
              memory: 500Mi
            requests:
              memory: 500Mi



---
# Source: auth/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: adminui
  namespace: {{ $.Release.Namespace }}
  labels: {}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: adminui
