apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adminui-ingress
  annotations:
    external-dns.alpha.kubernetes.io/alias: "true"
    external-dns.alpha.kubernetes.io/target: "thewatergategroups.com"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: "https://oauth2.thewatergategroups.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://oauth2.thewatergategroups.com/oauth2/start?rd=$scheme://$host$request_uri"
spec:
  tls:
  - hosts:
    - admin.thewatergategroups.com
    secretName: wildcard-watergate-tls
  rules:
  - host: admin.thewatergategroups.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: adminui
            port:
              number: 3000
