version: "3.9"
services:
  authui: 
    image: ghcr.io/thewatergategroups/authui:latest
    volumes:
      - ./web:/app
    network_mode: host
    env_file:
      - ./web/.env
    command: ["bun", "dev"]